site_name: research-tools-handbook
theme:
  name: material
site_url: https://yeahsupercool.github.io/research-tools-handbook/
nav:
  - Home: index.md
  - Remote Dev:
      - VS Code + SSH + tmux: recipes/vscode-ssh-tmux.md